### ISSUE TITLE
Create a Discord group （创建一个 Discord 讨论组）

### ISSUE THREAD

**Issue by chmod777john** [nus-apr/auto-code-rover#11]
Great job! How about creating a Discord discussion group so the community can have real-time discussions?
Just like https://github.com/princeton-nlp/SWE-agent?tab=readme-ov-file#-contributions-

**Comment by Marti2203** [comment]
Hi, we have made a  [Discord](https://discord.gg/7xqneXsu) group. Do join to chat! We will be actively monitoring :)
