### ISSUE TITLE
How to replay output?

### ISSUE THREAD

**Issue by yhuanghamu** [nus-apr/auto-code-rover#13]
In this [example.mp4](https://github.com/nus-apr/auto-code-rover/blob/main/results/examples/motivating/django__django-13933_2024-04-04_15-48-36/example.mp4) file, it  replay the planing and reasoning trajectories, but I can't find that mode in main execution file.

Can you show me some pointers to replay it?

Thanks

**Comment by crhf** [comment]
Just uploaded the script for that, see `scripts/replay`.

**Comment by yhuanghamu** [comment]
Thank  you
