### ISSUE TITLE
Adding a support for Cohere Command-R, Anthropic Claude, and Gemini APIs

### ISSUE THREAD

**Issue by adam2am** [nus-apr/auto-code-rover#15]
Hey, I would like to suggest support for integrating additional language model APIs beyond just OpenAI. Specifically, it would be very helpful to have the ability to use:

- Cohere API (including recent Command-R model with amazing retrieval-augmented generation)
- Anthropic API (Claude model)
- Google Gemini API 
- Ollama Local LLMs (for the sake of those, who can't share the code cuz of the NDA)

These models rank among the top 10 AI language models according to benchmarks like https://chat.lmsys.org/ and provide capabilities complementary to OpenAI's models.

The recent Command-R model from Cohere is particularly compelling for its strong retrieval-augmented capabilities using its embeddings. And the Claude model from Anthropic has received acclaim for its coherence and abilities to code.

Having this flexibility would be incredibly valuable. Would be amazing if you consider adding it!

**Comment by IvoP1** [comment]
It would be good to add AWS Bedrock API to that list. It supports Claude, LLama, etc...

**Comment by andr0s** [comment]
Just add litellm support. Everything already included there. No need to add support for each and every LLM and provider

**Comment by yuntongzhang** [comment]
We are currently working on the LiteLLM support. It should be ready sometime next week.

**Comment by stevensu1977** [comment]
> Just add litellm support. Everything already included there. No need to add support for each and every LLM and provider

LiteLLM is a great project, but some models have  no native support for function calling , etc. Amazon Bedrock Claude3

**Comment by andr0s** [comment]
@stevensu1977 well, the whole point is to have the ability to run open source and/or free things. Otherwise people would just be happy with ChatGPT and Claude 3, and this ticket wouldn't even exist

**Comment by yuntongzhang** [comment]
ACR now supports Claude models through LiteLLM and Llama3 through Ollama (added in https://github.com/nus-apr/auto-code-rover/pull/32). Feel free to try it out :)

**Comment by rezzie-rich** [comment]
can you please add support for any open LLM through liteLLM or ollama? currently, for code generation, codeQwen 1.5 7b is ranked as high as GPT-4 and it's only a 7b model so it can easily run locally pretty quickly.

**Comment by Marti2203** [comment]
Hi @rezzie-rich, justa added support for generic litellm in commit   bed6e775bdc701ca8c0242e072c5c2ac25098477 Ollama's been supported for a while now, will close the issue
