### ISSUE TITLE
Unable to add issue from github 

### ISSUE THREAD

**Issue by Rehan-shah** [nus-apr/auto-code-rover#16]
Hi so I added a custom issue (the one not in the  conf/swe_lite_tasks.txt file ) from GitHub and was getting this error

vercel__next.js-64413

`2024-04-12 17:11:58,722 - INFO - env_name for all setup entries: []
2024-04-12 17:11:58,722 - INFO - No setup needed..`

So what should I do?

**Comment by adzcai** [comment]
Hey, did you find a solution to this? I'd also like to add custom GitHub issues

**Comment by yuntongzhang** [comment]
Hi, I have just opened a [PR](https://github.com/nus-apr/auto-code-rover/pull/25) to support running ACR on new GitHub issues, which will probably be merged in a day or two.

Meanwhile, feel free to try it out and provide feedback if you have any!
