### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by PierrunoYT** [nus-apr/auto-code-rover#2]
(base) root@26c024020254:/opt/auto-code-rover# cd /opt/SWE-bench
(base) root@26c024020254:/opt/SWE-bench# echo opendevin__ssh-connection-issue-911 > tasks.txt
(base) root@26c024020254:/opt/SWE-bench# conda activate swe-bench
(swe-bench) root@26c024020254:/opt/SWE-bench# python harness/run_setup.py --log_dir logs --testbed testbed --result_dir setup_result --subset_file tasks.txt
2024-04-09 09:11:13,566 - INFO - env_name for all setup entries: []
2024-04-09 09:11:13,566 - INFO - No setup needed.
(swe-bench) root@26c024020254:/opt/SWE-bench# cd /opt/auto-code-rover
(swe-bench) root@26c024020254:/opt/auto-code-rover# conda activate auto-code-rover
(auto-code-rover) root@26c024020254:/opt/auto-code-rover# PYTHONPATH=. python app/main.py --enable-layered --model gpt-4-0125-preview --setup-map /opt/SWE-bench/setup_result/setup_map.json --tasks-map /opt/SWE-bench/setup_result/tasks_map.json --output-dir /mnt/c/Users/pierr/output --task opendevin__ssh-connection-issue-911
Traceback (most recent call last):
  File "/opt/auto-code-rover/app/main.py", line 477, in <module>
    main()
  File "/opt/auto-code-rover/app/main.py", line 399, in main
    with open(setup_map_file, "r") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/SWE-bench/setup_result/setup_map.json'
(auto-code-rover) root@26c024020254:/opt/auto-code-rover#

**Comment by yuntongzhang** [comment]
This task is not from SWE-bench. Currently the steps in README.md only work for tasks in SWE-bench (complete list at `conf/swe_full_tasks.txt`). 

To run a new task, the target project repo needs to be cloned and checked out locally. Then meta info like project path, commit hash and the issue descriptions need to be extracted and made available to AutoCodeRover. We are working on supporting this and hopefully it will be ready soon.

**Comment by PierrunoYT** [comment]
> This task is not from SWE-bench. Currently the steps in README.md only work for tasks in SWE-bench (complete list at `conf/swe_full_tasks.txt`).
> 
> To run a new task, the target project repo needs to be cloned and checked out locally. Then meta info like project path, commit hash and the issue descriptions need to be extracted and made available to AutoCodeRover. We are working on supporting this and hopefully it will be ready soon.

Hope it will be easier soon.

**Comment by 1of13** [comment]
For me, following the instructions after installing Miniconda3 worked. I'm on an M3 Mac.
