### ISSUE TITLE
Comments on PullRequestBenchmark?

### ISSUE THREAD

**Issue by mrconter1** [nus-apr/auto-code-rover#3]
Hello!

I am the author of [PullRequestBenchmark](https://github.com/mrconter1/PullRequestBenchmark/) and I am wondering if you have any thoughts on that?

Best Regards

**Comment by zhiyufan** [comment]
Thank you for building the benchmark, that looks interesting to me!
As of now, we are focusing on improving Auto-Code-Rover regarding the program repair and feature addition capabilities. There is a lot more to work on. We will consider the PR evaluation benchmark in the future!
So I'm going to close the issue for now. 

Thank you.

**Comment by mrconter1** [comment]
No problem! Thank you for sharing your thoughts!
