### ISSUE TITLE
swe_agent_rep

### ISSUE THREAD

**Issue by raminsharifi** [nus-apr/auto-code-rover#33]
Hello,
In your paper, how do you run swe agent in your docker env? I saw the comparison between your docker env and theirs.
Thank you

**Comment by zhiyufan** [comment]
1. Install ACR docker
2. Pull swe-agent repo in the ACR docker.
3. Be careful about the conda environment, swe-agent might install new conda environment, which may conflict with the existing conda environment in ACR docker.
5. Run swe-agent with cost-budget at 2 USD. Remember to remove the demo field from their configuration file.
4. After swe-agent finish execution, convert the all_pred.jsonl to all_pred.json.
5. Evaluate the result with ACR evaluation script, using the converted all_pred.json as input.

**Comment by raminsharifi** [comment]
Perfect. Thank you.
