### ISSUE TITLE
How to make it work without anaconda

### ISSUE THREAD

**Issue by MukkiiiNishu** [nus-apr/auto-code-rover#41]
Hi , Anaconda is blocked for my department, can I get any solution which can help me to use it just using python.

**Comment by yuntongzhang** [comment]
Hi, if conda is not available, one way is to extract the dependencies and install them with pip. This might be achievable using some small script (for example: https://stackoverflow.com/questions/72824468/pip-installing-environment-yml-as-if-its-a-requirements-txt). 

In the future we may support dependency management other than conda, but that is not a priority now.

**Comment by Marti2203** [comment]
Hi, I have added an exemplar requirements.txt in commit b12ddb8ee4ca8130f536307213fe9762a8f3fc5b, which is part of main. This should solve the issue. Moving forward we will be keeping the environment.yml aligned with requirements.txt
