### ISSUE TITLE
How to select the api？

### ISSUE THREAD

**Issue by HagonChan** [nus-apr/auto-code-rover#44]
What exactly should I do to select the api, is it via command line or shortcut?
![image](https://github.com/nus-apr/auto-code-rover/assets/77165006/4502ecdc-a1b6-414d-9f0b-05d9caf67780)

**Comment by yuntongzhang** [comment]
Hi, the API selection is done by the model. If there is no error, the model selected APIs will be displayed in the next step.

In your screenshot, it seems there is an API connection error, so there is no response from the model. May I know which model you are using?

**Comment by HagonChan** [comment]
gpt-4-0125-preview

**Comment by yuntongzhang** [comment]
Have you tried whether you can get a response from gpt just by sending a request from command line? Something like this: https://platform.openai.com/docs/quickstart?context=curl

The error you are experiencing is likely a connection issue to OpenAI APIs.

**Comment by Marti2203** [comment]
Hi @HagonChan ,
Just to check - have you had this issue subsequently? I think we can close it if it has gone stale.
