### ISSUE TITLE
docker install error 

### ISSUE THREAD

**Issue by hhn12138** [nus-apr/auto-code-rover#53]
![image](https://github.com/nus-apr/auto-code-rover/assets/92977136/91b62139-c921-425f-b2a4-092e076a9443)
This is a very good project, but when I install docker according to the readme, it doesn't work properly. It's a pity. Is there any solution?

**Comment by Marti2203** [comment]
Hi, you cannot pull from the Dockerhub repository due to a blocked TCP connection. Are perhaps you behind an enterprise network or firewall?
