### ISSUE TITLE
Add a new mode that only outputs fix locations

### ISSUE THREAD

**Issue by yuntongzhang** [nus-apr/auto-code-rover#56]
Sometimes we do not want to run the entire workflow to generate a patch. 

Add a new mode to exit after context retrieval stage, and output the visited locations (files, classes, methods) in a single file for users to inspect.

In addition, this mode should allow specifying a max context retrieval round number. Once that number is hit, the workflow should also be aborted. This is to avoid running too many rounds and to control the cost.

**Comment by Marti2203** [comment]
Implemented in 71da61d9e403634195c22e78d9020a4e8c452953
