### ISSUE TITLE
Expose openai.base_url for access to more models

### ISSUE THREAD

**Issue by talentoscope** [nus-apr/auto-code-rover#60]
It would be great if openai.base_url was exposed so that nearly any model could be loaded in via lm-studio or other OpenAI-like APIs.

**Comment by Marti2203** [comment]
Hi, I just added support for changing the base URL in the LiteLLM GPT model in commit 1b47dda4

**Comment by talentoscope** [comment]
Amazing, thank you!

**Comment by Marti2203** [comment]
Will close the issue then if all is good :+1:
