### ISSUE TITLE
Task django__django-11133 failed with exception: RetryError[<Future at 0x7f0b27f3ebd0 state=finished  raised AuthenticationError>].

### ISSUE THREAD

**Issue by HagonChan** [nus-apr/auto-code-rover#63]
The openai api can be requested normally, but it doesn't seem to be requested when ACR is making a request?

error:Task django__django-11133 failed with exception: RetryError[<Future at 0x7f0b27f3ebd0 state=finished  raised AuthenticationError>].
![image](https://github.com/user-attachments/assets/a4779f19-b576-4e51-b3e8-963f4c19a9a9)

**Comment by Marti2203** [comment]
Hi, there is an info.log file containing more details of the exception. Can you share them?

**Comment by HagonChan** [comment]
[info.log](https://github.com/user-attachments/files/17000685/info.log)
This is the output log.

**Comment by Marti2203** [comment]
In the file I see that this is the underlying exception that stopped the execution:
```openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A**_KEY. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}```
AutoCodeRover reads the variable `OPENAI_KEY` and uses that as the key. Are you sure that things are set up correctly?

**Comment by HagonChan** [comment]
yes, in the same environment, the openai request test is correctly

**Comment by Marti2203** [comment]
There is a difference between the `OPENAI_KEY` environment variable, which we read to pass to the OpenAI object, and the `OPENAI_API_KEY` environment variable, which is read by openai if you do not pass an argument to the constructor [Link to the respective lines](https://github.com/nus-apr/auto-code-rover/blob/9da051510f721e177b846017797603569708dc99/app/model/gpt.py#L74)

**Comment by HagonChan** [comment]
OMG, that was my problem, it's fixed now, thanks!

**Comment by Marti2203** [comment]
No problem :) happy to hear that all is good!
