### ISSUE TITLE
C drive is full of memory when running command "docker build -f Dockerfile -t acr ."

### ISSUE THREAD

**Issue by minhnhatle104** [nus-apr/auto-code-rover#71]
Dear team,

I am facing an issue and I hope you can help me to clarify it: 
I am using DELL laptop ( Windows 11) and my C Drive has 39 GB empty. 
I tried to run your auto-code-rover in my local laptop but when using  "docker build -f Dockerfile -t acr .", it reached to **step 14: RUN conda env create -f environment.yml**
--> My C drive is out of memory ( 39 GB was consumed and there was 0 GB left). Then all the docker build was failed.

Please help me with this problem

**Comment by Marti2203** [comment]
Hi, I suggest building with the Dockerfile.minimal as that would require a lot less space. The Dockerfle constructs a version of AutoCodeRover that contains setup to evaluate the tool's capabilities on SWE-Bench

**Comment by minhnhatle104** [comment]
Hi @Marti2203 , after running Dockerfile.minimal. It worked now. But, then I found another problems:
I can not find opt/SWE_bench when using **cd /opt/SWE_bench** and also cannot activate environment SWE_bench. **( conda activate SWE_bench)**

Could you please help me with this problem ?

**Comment by Marti2203** [comment]
Hi, Dockerfile.minimal does not contain any setup for SWE-bench. I misunderstood from our last discussion that you do not need SWE-Bench. I think that you will need to allocate space for the larger image.

**Comment by minhnhatle104** [comment]
hi @Marti2203 , thanks for your clarification, I can run it now. I will close the issue
