### ISSUE TITLE
Why some instances get Error running command: git returned non-zero exit status 128 and how to fix it?

### ISSUE THREAD

**Issue by 27yw** [nus-apr/auto-code-rover#76]
Thanks for your work.

Here when I try to test auto_code_rover on random selected 100 instances some got this kind of error:

`Error running command: ['git', 'reset', '--hard', 
'04ac9b45a34440fa447feb6ae934687aacbfc5f4'], Command '['git', 'reset', '--hard',
'04ac9b45a34440fa447feb6ae934687aacbfc5f4']' returned non-zero exit status 128.`

**but some other instances won't**

e.g. [2024-11-17 19:09:18] ============= Running task django__django-11885 =============
Error running command: ['git', 'reset', '--hard', 
'04ac9b45a34440fa447feb6ae934687aacbfc5f4'], Command '['git', 'reset', '--hard',
'04ac9b45a34440fa447feb6ae934687aacbfc5f4']' returned non-zero exit status 128.

how to fix it?
all this instances have already been setup with the instructions from [https://github.com/yuntongzhang/SWE-bench.git](url)

very urgent and thank you for your help!

**Comment by Marti2203** [comment]
Hi,
I tried reproducing it with the latest master branch commit but was unsuccessful. 
May I know what OS you are trying this execution on?

**Comment by 27yw** [comment]
Hi, I use linux on A800 same to AWS
and I try to use the test set of swe-bench

**Comment by 27yw** [comment]
More information:
I figure out the question are caused by this function in utils.py
`def repo_reset_and_clean_checkout(commit_hash: str) -> None:
    """
    Run commands to reset repo to the original commit state.
    Cleans both the uncommited changes and the untracked files, and submodule changes.
    Assumption: The current directory is the git repository.
    """
    # NOTE: do these before `git reset`. This is because some of the removed files below
    # may actually be in version control. So even if we deleted such files here, they
    # will be brought back by `git reset`.
    # Clean files that might be in .gitignore, but could have been created by previous runs
    # print("here in line 137 in utils")`

any help?

**Comment by Marti2203** [comment]
Hi, can you remove the DEVNULL assignments in `run_command(reset_cmd,stdout=DEVNULL,stderr=DEVNULL)`? That will print out the error

**Comment by 27yw** [comment]
hi I got this error
`d16bfe05a744909de4b27f5875fe0d4ed41ce607
fatal: 不能解析对象 'd16bfe05a744909de4b27f5875fe0d4ed41ce607'。
Error running command: ['git', 'reset', '--hard', 
'd16bfe05a744909de4b27f5875fe0d4ed41ce607'], Command '['git',
'reset', '--hard', 
'd16bfe05a744909de4b27f5875fe0d4ed41ce607']' returned 
non-zero exit status 128.`

and I have check one thing which is wired
in the [https://github.com/yuntongzhang/SWE-bench.git](url) we setup the env successfully but the testbed folder seems to contain nothing
<img width="467" alt="截屏2024-11-18 14 08 10" src="https://github.com/user-attachments/assets/a3d66cc5-2e4c-410a-a0eb-95a2cf50e82e">
while some contains files
<img width="427" alt="截屏2024-11-18 14 08 44" src="https://github.com/user-attachments/assets/7fdb1c8f-4916-414d-86a2-1915c4562735">

**Comment by Marti2203** [comment]
Can you try rebuilding astropy 1.3? Maybe there was some fault?

**Comment by 27yw** [comment]
still nothing in the files
and logs says
`2024-11-18 15:30:24,007 - INFO - [setup_astropy__astropy__1.3] ======= Start setting up for astropy/astropy 1.3 =======
2024-11-18 15:30:34,460 - INFO - [setup_astropy__astropy__1.3] Cloned astropy/astropy to /data_train/code/biz/yw/swe/code1/SWE-bench_from_github/testbed/astropy__astropy/setup_astropy__astropy__1.3
2024-11-18 15:30:37,820 - INFO - [setup_astropy__astropy__1.3] Removing old conda env setup_astropy__astropy__1.3
2024-11-18 15:32:42,989 - INFO - [setup_astropy__astropy__1.3] Creating environment setup_astropy__astropy__1.3; Command: /data_train/code/biz/yw/miniconda3/bin/conda create -n setup_astropy__astropy__1.3 python=3.9  -y
2024-11-18 15:33:37,035 - INFO - [setup_astropy__astropy__1.3] Created conda environment setup_astropy__astropy__1.3 for astropy/astropy 1.3
`

I am really confused.

**Comment by 27yw** [comment]
<img width="502" alt="截屏2024-11-18 15 45 57" src="https://github.com/user-attachments/assets/e23fd66a-c182-43c5-8122-fbed93addd06">
still nothing that is wired.

how to fix it?

**Comment by Marti2203** [comment]
Can you open 
https://github.com/yuntongzhang/SWE-bench/blob/main/harness/run_setup.py on your side and for line 231, make the following change.
```
if not  clone_repo(repo_full, repo_path):
   print("failed to clone")
```

**Comment by Marti2203** [comment]
I see, so you are in a network that has blocked access to the repository...

**Comment by Marti2203** [comment]
Happy to hear that things are being solved :) good luck!
