### ISSUE TITLE
Broken image yuntongzhang/swe-bench:latest

### ISSUE THREAD

**Issue by boomerango** [nus-apr/auto-code-rover#9]
Not possible to install libs to the image

$DPKG_HOOK_ACTION" = remove-architecture; } && test -x /usr/share/pkg-config-dpkghook; then /usr/share/pkg-config-dpkghook update; fi', exit code 32512
E: Sub-process /usr/bin/dpkg returned an error code (2)
E: Problem executing scripts DPkg::Post-Invoke 'if [ -d /var/lib/update-notifier ]; then touch /var/lib/update-notifier/dpkg-run-stamp; fi; /usr/lib/update-notifier/update-motd-updates-available 2>/dev/null || true'
E: Sub-process returned an error code
The command '/bin/sh -c apt install -y vim build-essential libssl-dev' returned a non-zero code: 100

**Comment by yuntongzhang** [comment]
Could you provide the list of commands used and the system environment so that we can try to reproduce the issue?

**Comment by boomerango** [comment]
@yuntongzhang  just build 
docker build -f Dockerfile -t acr .

**Comment by boomerango** [comment]
@yuntongzhang  then next error from conda

Retrieving notices: ...working... failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/root/miniconda3/lib/python3.12/site-packages/conda/exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/root/miniconda3/lib/python3.12/site-packages/conda/cli/main.py", line 83, in main_subshell
        exit_code = do_call(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^
      File "/root/miniconda3/lib/python3.12/site-packages/conda/cli/conda_argparse.py", line 196, in do_call
        result = getattr(module, func_name)(args, parser)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/miniconda3/lib/python3.12/site-packages/conda/notices/core.py", line 108, in wrapper
        channel_notice_set = retrieve_notices(
                             ^^^^^^^^^^^^^^^^^
      File "/root/miniconda3/lib/python3.12/site-packages/conda/notices/core.py", line 40, in retrieve_notices
        channel_notice_responses = fetch.get_notice_responses(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/miniconda3/lib/python3.12/site-packages/conda/notices/fetch.py", line 44, in get_notice_responses
        for chn_info in executor.map(
                        ^^^^^^^^^^^^^
      File "/root/miniconda3/lib/python3.12/concurrent/futures/_base.py", line 608, in map
        fs = [self.submit(fn, *args) for args in zip(*iterables)]
              ^^^^^^^^^^^^^^^^^^^^^^
      File "/root/miniconda3/lib/python3.12/concurrent/futures/thread.py", line 179, in submit
        self._adjust_thread_count()
      File "/root/miniconda3/lib/python3.12/concurrent/futures/thread.py", line 202, in _adjust_thread_count
        t.start()
      File "/root/miniconda3/lib/python3.12/threading.py", line 992, in start
        _start_new_thread(self._bootstrap, ())
    RuntimeError: can't start new thread

`$ /root/miniconda3/bin/conda env create -f environment.yml`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=/root/miniconda3
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/root/miniconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
                          :/sbin:/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /root/.condarc
 populated config files : 
          conda version : 24.1.2
    conda-build version : not installed
         python version : 3.12.1.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=haswell
                          __conda=24.1.2=0
                          __glibc=2.35=0
                          __linux=4.19.76=0
                          __unix=0=0
       base environment : /root/miniconda3  (writable)
      conda av data dir : /root/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /root/miniconda3/pkgs
                          /root/.conda/pkgs
       envs directories : /root/miniconda3/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/24.1.2 requests/2.31.0 CPython/3.12.1 Linux/4.19.76-linuxkit ubuntu/22.04.4 glibc/2.35 solver/libmamba conda-libmamba-solver/23.12.0 libmambapy/1.5.3
                UID:GID : 0:0
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

The command '/bin/sh -c conda env create -f environment.yml' returned a non-zero code: 1

**Comment by yuntongzhang** [comment]
The build command runs fine on my system. I can't reproduce the second error as well.

What system are you using? Did the disk run out of space? Just guessing for possibilities here.

There are some posts on apt error when building from Dockerfile, which might be helpful:
https://stackoverflow.com/questions/38002543/apt-get-update-returned-a-non-zero-code-100

**Comment by boomerango** [comment]
Host is macos, disk space is enough, cpu limit is 6, disk unlimited.

**Comment by boomerango** [comment]
OK, solved. 
Had to change base image and use more stable python 

for ref
FROM ubuntu:focal

# # Add the missing GPG key 871920D1991BC93C
RUN apt-get update && apt-get install -y gnupg && \
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 871920D1991BC93C

# Update and install necessary packages
RUN apt update && apt install -y gnupg

RUN apt-get -y update

RUN apt update && apt install -y git wget

WORKDIR /root
# RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-py311_24.1.2-0-Linux-x86_64.sh
RUN bash ./Miniconda3-py311_24.1.2-0-Linux-x86_64.sh -b -p /root/miniconda3
ENV PATH="/root/miniconda3/bin:${PATH}"
RUN conda init

WORKDIR /opt
RUN git clone https://github.com/yuntongzhang/SWE-bench.git

WORKDIR /opt/SWE-bench
RUN conda env create -f environment.yml
RUN ln -sf /bin/bash /bin/sh

ENV DEBIAN_FRONTEND=noninteractive
RUN apt install -y libffi-dev python3-pytest libfreetype6-dev libqhull-dev
RUN apt install -y pkg-config texlive cm-super dvipng python-tk ffmpeg
RUN apt install -y imagemagick fontconfig
RUN apt install -y ghostscript inkscape graphviz
RUN apt install -y optipng fonts-comic-neue  python3-pikepdf

RUN echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections
RUN apt install -y ttf-mscorefonts-installer

RUN apt install -y vim build-essential libssl-dev

RUN git config --global user.email acr@nus.edu.sg
RUN git config --global user.name acr

COPY . /opt/auto-code-rover
WORKDIR /opt/auto-code-rover
RUN conda env create -f environment.yml
